# Generated by Django 5.0.4 on 2024-04-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='choice_1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='choices',
            name='choice_2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='choices',
            name='choice_3',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='choices',
            name='choice_4',
            field=models.CharField(max_length=150),
        ),
    ]
