# Generated by Django 5.0.4 on 2024-04-29 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_alter_choices_choice_1_alter_choices_choice_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice1', to='quiz_app.choices')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='que_attempted', to='quiz_app.question')),
                ('user_leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.leaderboard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
