# Generated by Django 5.0.4 on 2024-04-29 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempted',
            name='user_leaderboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempt', to='quiz_app.leaderboard'),
        ),
    ]
